#!/usr/bin/env python3
"""Break one thing at a time in a copy of the tree; every break must turn a test red.

A test suite can pass because it asserts what happens to be true rather than what
the code is for. This runs each listed mutation against a fresh copy of the tree
and reports any that no test objects to. Run it after changing a guard:

    runner/tests/mutate.py            # every mutation
    runner/tests/mutate.py noflock    # one, by name
"""
import io, os, re, shutil, subprocess, sys, tempfile

SRC = os.path.dirname(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
# somewhere with room for a copy of the tree per mutation; not /tmp, which is
# RAM on the review box
WORK = os.environ.get("REVIEW_MUTATE_DIR") or tempfile.gettempdir()
RUN = "runner/bin/run-reviewprs.sh"
AUT = "runner/bin/review-auth.sh"
ENV = "runner/bin/review-env.sh"
BOTH = (RUN, AUT)
PAGE = "runner/bin/make-runs-page.py"
QUO = "runner/bin/quota.py"
PRB = "runner/bin/claude-usage-probe.sh"
ACC = "runner/bin/accounts.py"
MIG = "runner/bin/migrate-auth-root.sh"

# name -> (file(s), old, new)   old must appear exactly once in each file
M = [
 ('migancestor', MIG, 'if inside(review, new):', 'if False:'),
 ('migcontrol', MIG, 'if any(ord(c) < 32 for c in new):', 'if False:'),
 ('migchmod', MIG, 'if stat.S_IMODE(os.stat(new).st_mode) != 0o700:', 'if True:'),
 ('migatomic', MIG, '        regular(path)\n        os.replace(tmp, path)',
                  '        regular(path)\n        open(path, "wb").write(updated[:10])\n        os.replace(tmp, path)'),
 ('migwalk', MIG, 'os.walk(root, followlinks=False, onerror=unreadable)', 'os.walk(root, followlinks=False)'),
 ('authowninside', ENV, '        account_outside_review "$HOME/.$tool" || return 2\n', ''),
 ('authtargetinside', ENV, '    account_outside_review "$target" || return 2\n', ''),

 ('reresolve', RUN, 'd=$(role_config_dir "$tool" "$ROLE" "$d")',
                   'd=$(role_config_dir "$tool" "$ROLE")'),
 ('denyfsroot', RUN, '    if path == "/":', '    if False:'),
 ('denytilderoot', RUN, '    elif path == "~":', '    elif False:'),
 ('denydot', RUN, 'any(part in (".", "..") for part in path.split("/"))',
                  'False'),
 ('baretool', RUN, 'def denies_auth(rule):',
                  'def denies_auth(rule):\n    if rule == "Read":\n        return True'),
 ('denylist', RUN, 'if not isinstance(deny, list) or not all(isinstance(r, str) for r in deny):',
                  'if False:'),
 ('ruleunescape', RUN, 'path = rule[5:-4].replace("\\\\\\\\", "\\\\")',
                  'path = rule[5:-4]'),
 ('ruleescape', RUN, '    pattern = pattern.replace("\\\\\\\\", "\\\\\\\\\\\\\\\\")\n',
                  ''),
 ('loginescapelevel', AUT, 'auth = auth.replace("\\\\\\\\", "\\\\\\\\\\\\\\\\")\n',
                  ''),
 ('unusedprovider', ENV, '                if key == "model_providers" and name != "openai":',
                  '                if False:'),
 ('probebroken', PRB, 'if [ "$PROBE_RC" -eq 2 ]; then',
                  'if false; then'),
 ('probeownrun', PRB, ' && [ -z "${REVIEW_ROLE:-}" ]',
                  ''),
 ('quotaglob', PAGE, "glob.escape(directory), 'sessions'",
                  "directory, 'sessions'"),
 ('authglob', QUO, 'glob.escape(AUTH), tool + "-*"',
                  "AUTH, tool + '-*'"),
 ('claudeglob', PAGE, "os.path.join(glob.escape(r), sub) for r in account_dirs('claude')",
                  "os.path.join(r, sub) for r in account_dirs('claude')"),
 ('logglob', PAGE, "glob.escape(LOGS), 'reviewprs-*.log'",
                  "LOGS, 'reviewprs-*.log'"),
 ('quotadeleted', PAGE, '    samples = []',
                  '    samples = quota if directory and not os.path.isdir(directory) else []'),
 ('denysubstring', RUN, 'any(denies_auth(r) for r in deny)', 'any(auth in r or "review.auth" in r for r in deny)'),
 ('denyescaping', RUN, 'pattern = re.sub(r"([\\\\*?\\[\\]])", r"\\\\\\1", os.path.realpath(auth))', 'pattern = os.path.realpath(auth)'),
 ('loginescaping', AUT, 'auth = re.sub(r"([\\\\*?\\[\\]])", r"\\\\\\1", os.path.realpath(sys.argv[1]))', 'auth = os.path.realpath(sys.argv[1])'),
 ('permissionfinish', RUN, '    echo "finish=$(date -Is) status=preflight-failed"\n', ''),
 ('workfinish', RUN, '    echo "finish=$(date -Is) status=no-work-dir"\n', ''),
 ('pageterminal', PAGE, "elif re.search(r'status=(preflight-failed|no-work-dir)\\b', txt):", 'elif False:'),
 ('pagefailcount', PAGE, "'wrong-account', 'preflight-failed',\n                                               'no-work-dir', 'account-policy'))", "'wrong-account'))"),
 ('denytool', RUN, 'not rule.startswith("Read(")', 'False'),
 ('denycoverage', RUN, 'os.path.commonpath([root, os.path.realpath(auth)]) == root', 'True'),
 ('denyancestor', RUN, 'os.path.commonpath([root, os.path.realpath(auth)]) == root', 'root == os.path.realpath(auth)'),
 ('denysuggestion', RUN, 'json.dumps("Read(/%s/**)" % pattern)', 'json.dumps("Read(%s/**)" % pattern)'),
 ('loginsettings', AUT, '"Bash(git push)", "Bash(git push:*)", "Read(/%s/**)" % auth', '"Bash(git push)", "Bash(git push:*)", "Read(%s/**)" % auth'),
 ('installsettings', "docs/review-box.md", '"Read(~/review.auth/**)"', '"Edit(~/review.auth/**)"'),
 ('readmesettings', "README.md", '"Read(~/review.auth/**)"', '"Edit(~/review.auth/**)"'),
 ('usetool', AUT, '    tool="$2"; role="$3"; acct="$4"\n    case "$tool" in claude|codex) ;; *) echo "unknown tool: $tool"; exit 2 ;; esac', '    tool="$2"; role="$3"; acct="$4"'),
 ('logintool', AUT, '    tool="$2"; acct="$3"\n    case "$tool" in claude|codex) ;; *) echo "unknown tool: $tool"; exit 2 ;; esac', '    tool="$2"; acct="$3"'),
 ('plainname', AUT, 'plain_name() {', 'plain_name() { return 0; }\nunused_plain_name() {'),
 ('rolealias', AUT, '{ [ "$already" = 0 ] && [ -L "$dir" ] && \\\n         [ "$(readlink -f "$dir")" = "$(readlink -f "$link")" ]; }', 'false'),
 ('quotaenv', PAGE, "_codex_pick = role_dir('codex')", "_codex_pick = os.environ.get('CODEX_HOME') or role_dir('codex')"),
 ('quotamixed', PAGE, 'samples = codex_quotas[directory][0]', 'samples = quota'),
 ('quotaunknown', PAGE, '    samples = []', '    samples = quota'),
 ('quotaidentity', PAGE, "codex_identity(directory) == r.get('codex_account')", 'True'),
 ('quotadangling', PAGE, "os.path.lexists(link) or role != 'default'", "role != 'default'"),
 ('quotaown', PAGE, "    return os.path.realpath(os.path.join(HOME, '.' + tool))", '    return None'),
 ('quotalabel', PAGE, 'html.escape(quota_role)', "''"),
 ('quotaspace', PAGE, 'home (.+)\\)$', 'home (\\S+)\\)$'),
 ("rootowner", ENV, ' -o ! -user "$(id -u)"', ''),
 ("unknownid", RUN, 'if [ -z "$ACCOUNT" ]; then', 'if false; then'),
 ("rejectcodex", RUN, '[ "$CODEX_ACCOUNT" != "$WANT" ]', 'false'),
 ("disagree", RUN, '[ "$CLAUDE_CLI_ACCOUNT" != "$CLAUDE_REC_ACCOUNT" ]', 'false'),
 ("badrecord", RUN, 'WANT=$(read_account_file "$CLAUDE_DIR/ACCOUNT")',
                    'WANT=$(read_account_file "$CLAUDE_DIR/ACCOUNT" || true)'),
 ("noflock", AUT, 'flock 9 ||', 'true 9 ||'),
 ("earlyrelease", AUT, 'was=$(readlink "$link"', 'exec 9>&-; was=$(readlink "$link"'),
 ("noduddash", AUT, 'ln -sfn -- "$was"', 'ln -sfn "$was"'),
 ("noswitchback", AUT, 'ln -sfn -- "$was" "$tmp2"', 'true "$was" "$tmp2"'),
 ("lyingrevert", AUT, 'if [ "$back" = 1 ]; then', 'if true; then'),
 ("nolocksymlink", AUT, '[ ! -L "$lockf" ] ||', '[ 1 = 1 ] ||'),
 ("norootfirst", AUT, '    auth_root_ok || { echo "refusing to switch"; exit 1; }\n', ''),
 ("nostatusrec", AUT, 'note="  BAD ACCOUNT RECORD - runs will refuse"', 'true'),
 ("noconflict", AUT, '&& note="  CONFLICT: directory records $rec - runs will refuse"', '&& true'),
 ("alwaysconflict", AUT, '[ -n "$rec" ] && [ "$rec" != "$got" ]', '[ -n "$rec" ]'),
 ("nomismatch", AUT, '&& note="  MISMATCH: expected $want - runs will refuse" ;;', '&& true ;;'),
 ("noidunknown", AUT, '*:"signed in")', '*:"never happens")'),
 ("nodefaultrow", AUT, 'if [ "$rc" -eq 1 ]; then', 'if false; then'),
 ("statusapikey", AUT, 'elif [ "$got" = api-key ]; then', 'elif false; then'),
 ("statusmethod", AUT, '(got.get("authMethod") or "claude.ai") != "claude.ai"', 'False'),
 ("statusprovider", AUT, '(got.get("apiProvider") or "firstParty") != "firstParty"', 'False'),
 ("statusdir", AUT, 'print("wrong-directory"); raise SystemExit', 'pass'),
 ("statuspartial", AUT, 'if sum(1 for k in keys if got.get(k)) != 3:', 'if False:'),
 ("statusfailedunset", AUT, 'if ! clear_inherited_credentials; then',
                            'clear_inherited_credentials; if false; then'),
 ("statusstderr", AUT, 'dir=$(review_auth "$tool" "$role" 2>/dev/null); rc=$?',
                       'dir=$(review_auth "$tool" "$role" 2>&1); rc=$?'),
 ("blindaccount", AUT, 'account_of() {', 'account_of() { echo ""; return 0; }\nunused_of() {'),
 ("lazyswitch", AUT, 'mv -T "$tmp" "$link" ||',
                     '[ "$(readlink "$link")" = "$tool-$acct" ] && exit 0; mv -T "$tmp" "$link" ||'),
 ("noenvsweep", ENV, 'for v in $CLEARED_VARS; do', 'for v in ; do'),
 ("nounsetcheck", ENV, '        [ -z "${!v+x}" ] || CLEARED_FAILED="$CLEARED_FAILED $v"\n', ''),
 ("skipunsets", ENV, '        unset "$v" 2>/dev/null || true\n',
                     '        case "$v" in OPENAI_*|CODEX_*) ;; *) unset "$v" 2>/dev/null || true ;; esac\n'),
 ("suffixgap", ENV, '\\|USE_[A-Z0-9_]\\{1,\\}\\)[A-Z0-9_]*', '\\|USE_[A-Z0-9_]\\{1,\\}\\)'),
 ("noopenai", ENV, '\\(ANTHROPIC\\|OPENAI\\)', '\\(ANTHROPIC\\)'),
 ("nocodex", ENV, '\\(CLAUDE\\|CODEX\\)_[A-Z0-9_]*\\(', '\\(CLAUDE\\)_[A-Z0-9_]*\\('),
 ("nofallbackpin", ENV, '[ -n "$d" ] && [ "$d" = "$(readlink -f "$own" 2>/dev/null)" ] \\\n        && [ ! -L "$own" ] && d=""',
                        '[ -n "$d" ] && [ "$d" = "$(readlink -f "$own" 2>/dev/null)" ] && d=""'),
 ("nomethod", RUN, '    claude.ai|-) ;;', '    *) ;;'),
 ("noprovider", RUN, '    firstParty|-) ;;', '    *) ;;'),
 ("noclidir", RUN, 'if [ "$CLAUDE_CLI_DIR" != "-" ]', 'if false && [ "$CLAUDE_CLI_DIR" != "-" ]'),
 ("partialmeta", RUN, 'if [ "$CLAUDE_META" != 3 ]; then', 'if false; then'),
 ("codexprovider", RUN, 'if [ -n "$CODEX_PROVIDER" ]; then', 'if false; then'),
 ("codexapikey", ENV, '(mode or "").lower() in ("apikey", "api_key")', 'False'),
 ("implicitkey", ENV, 'd.get("OPENAI_API_KEY") and not mode', 'False'),
 ("nourlscan", ENV, '            if not safe_url(v):', '            if False:'),
 ("noenvkey", ENV, '        if key in ("env_key",',
                    '        if False and key in ("env_key",'),
 ("noreqauth", ENV, '        elif key == "requires_openai_auth" and v is not True:', '        elif False:'),
 ("noprofileprov", ENV, '        elif key == "model_provider" and v != "openai":', '        elif False:'),
 ("nounreadable", ENV, '        print("unreadable-config")\n        raise SystemExit',
                       '        raise SystemExit'),
 ("fieldsplit", RUN,
   '{ IFS= read -r CLAUDE_LOGGED; IFS= read -r CLAUDE_CLI_ACCOUNT; IFS= read -r CLAUDE_METHOD\n'
   '  IFS= read -r CLAUDE_PROVIDER; IFS= read -r CLAUDE_CLI_DIR; IFS= read -r CLAUDE_META; } <<EOS',
   'read -r CLAUDE_LOGGED CLAUDE_CLI_ACCOUNT CLAUDE_METHOD CLAUDE_PROVIDER '
   'CLAUDE_CLI_DIR CLAUDE_META <<EOS'),
 ('urlscheme', ENV, 'u.scheme == "https"', 'u.scheme in ("http", "https")'),
 ('urlport', ENV, 'u.port in (None, 443)', 'True'),
 ('mcpfalsepositive', ENV, '        elif provider and isinstance(v, (dict, list)):', '        elif key == "mcp_servers":\n            bad.append(setting)\n        elif provider and isinstance(v, (dict, list)):'),
 ('bearertoken', ENV, '"experimental_bearer_token", "auth", "aws", "query_params"', '"unused", "auth", "aws", "query_params"'),
 ('credstore', ENV, 'key == "cli_auth_credentials_store" and v != "file"', 'False'),
 ('forcedlogin', ENV, 'key == "forced_login_method" and v != "chatgpt"', 'False'),
 ('danglingconfig', ENV, 'os.path.lexists(path)', 'os.path.exists(path)'),
 ('statusdetail', AUT, '                other=$(check_codex_config "$dir")', '                other=$(check_codex_config "$dir"); other=${other%%:*}'),
 ('statusshape', AUT, '*) note="  MISMATCH: expected $want - runs will refuse" ;;', '*) note="  (recorded $want, reported differently)" ;;'),
 ('statusunsafeprobe', AUT, 'runs will refuse:$CLEARED_FAILED"\n    exit 1', 'runs will refuse:$CLEARED_FAILED"'),
 ('cliexit', RUN, 'reply=$(claude auth status --json 2>/dev/null) || reply=""', 'reply=$(claude auth status --json 2>/dev/null) || true'),
 ('statusexit', AUT, 'if out.returncode != 0:', 'if False:'),
 ('metacontrol', BOTH, 'any(ord(c) < 32 or ord(c) == 127 for c in v)', 'False'),
 ('metaempty', BOTH, 'if k != "email" and (not v or v == "-"):', 'if False:'),
 ('metaloggertype', RUN, 'type(d.get("loggedIn")) is not bool', 'False'),
 ('statusloggertype', AUT, 'type(got.get("loggedIn")) is not bool', 'False'),
 ('metawhitespace', RUN, 'IFS= read -r CLAUDE_CLI_DIR', 'read -r CLAUDE_CLI_DIR'),
 ('cliidentity', BOTH, 'raise ValueError("invalid email")', 'pass'),
 ('recordidentity', RUN, 'print("invalid-record")', 'print(email)'),
 ('staterecordidentity', AUT, '    print("invalid-record")\nelse:\n    print(email)', '    print(email)\nelse:\n    print(email)'),
 ('codextokens', ENV, '    if not all(isinstance(tok.get(k), str) and tok[k]', '    if False and not all(isinstance(tok.get(k), str) and tok[k]'),
 ('codexmode', ENV, 'if mode not in (None, "chatgpt"):', 'if False:'),
 ('codexidentity', ENV, 'raise ValueError("missing account id")', 'pass'),
 ("nometa", RUN, 'if [ "$CLAUDE_META" != 3 ]; then',
                 'if [ "$CLAUDE_META" != 0 ] && [ "$CLAUDE_META" != 3 ]; then'),
 ("statusnometa", AUT, 'if sum(1 for k in keys if got.get(k)) != 3:',
                      'if sum(1 for k in keys if got.get(k)) not in (0, 3):'),
 ("rolecase", RUN, 'case "$(printf %s "$MODE" | tr "[:upper:]" "[:lower:]")" in\n    rsync|rsyncproject',
                  'case "$MODE" in\n    rsync|rsyncproject'),
 ("roleurl", RUN, '|https://github.com/rsyncproject/rsync/pull/*', ''),
 ("mcpcallback", ENV, 'key == "mcp_oauth_callback_url" and not provider', 'False'),
 ("codexjwt", ENV, '    parts = tok["id_token"].split(".")', '    parts = ["e30", "e30", "stub"]'),
 ("urlparser", ENV, '        u = urlsplit(value)\n        return (isinstance(value, str) and not re.search(r"[\\s\\\\]", value)\n                and u.scheme == "https" and u.hostname in OK_HOSTS\n                and u.username is None and u.password is None\n                and u.port in (None, 443) and not u.query and not u.fragment)',
                    '        m = re.match(r"https?://([^/:]+)", value.strip())\n        return not m or m.group(1) in OK_HOSTS'),
 ("oneconfiglayer", ENV, 'paths += sorted(glob.glob(', 'paths += list((lambda *a: [])('),
 ("otelscan", ENV, '        elif isinstance(v, dict):\n            # Every other table too',
                   '        elif False:\n            # Every other table too'),
 # credentials moved inside the directory the reviewing agent is given
 ("nocreddeny", RUN, 'if auth and not any(denies_auth(r) for r in deny):',
                     'if False:'),
 ("credrealpath", PAGE, '_files.setdefault(os.path.realpath(_f), _f)',
                        '_files.setdefault(_f, _f)'),
 # the one-time move of the accounts
 ('migmerge', MIG, 'if moving and os.path.lexists(destination):',
                  'if False:'),
 ('migstale', MIG, 'permissions["deny"] = deny + [want]',
                  'permissions["deny"] = [r for r in deny if "review/auth" not in r and r != "Read(~/review/**)"] + [want]'),
 ('migdry', MIG, 'if args.dry_run:',
                  'if False:'),
 ('migprevalidate', MIG, 'raise ValueError("invalid settings: %s (%s)" % (path, e)) from None',
                  'continue'),
 ('migexit', MIG, '    sys.exit(1)',
                  '    sys.exit(0)'),
 ('migresume', MIG, '    root = old if moving else new',
                  '    if not moving:\n        return\n    root = old if moving else new'),
 ('migrepeat', MIG, '        if want in deny:',
                  '        if False:'),
 ('migglob', MIG, 'os.path.join(glob.escape(root), "claude-*")',
                  'os.path.join(root, "claude-*")'),
 ('migpattern', MIG, '    pattern = re.sub(r"([\\\\*?\\[\\]])", r"\\\\\\1", pattern)\n',
                  ''),
 ('migoutsidehome', MIG, 'else "/" + new',
                  'else "~/" + os.path.relpath(new, home)'),
 ('migcanonical', MIG, '    new = os.path.realpath(destination)',
                  '    new = destination'),
 ('migrootlink', MIG, 'if os.path.islink(old) or os.path.islink(destination):',
                  'if False:'),
 ('migdevice', MIG, 'if moving and os.stat(root).st_dev != os.stat(os.path.dirname(new)).st_dev:',
                  'if False:'),
 ('migcopy', MIG, '        os.rename(old, new)',
                  '        __import__("shutil").move(old, new)'),
 ('migpostcheck', MIG, 'if inside(os.path.realpath(new), review):',
                  'if False:'),
 ('migabslink', MIG, 'if os.path.isabs(value) and inside(target, old):',
                  'if False:'),
 ('migrellink', MIG, 'if not os.path.isabs(value) and not inside(direct, old):',
                  'if False:'),
 ('migownlink', MIG, 'elif inside(target, old):',
                  'elif False:'),
 ('migdangling', MIG, 'if not os.path.exists(link):',
                  'if False:'),
 ('migdestination', MIG, '    if os.path.lexists(path):\n        regular(path)',
                  '    pass'),
 ('migtemp', MIG, '    fd, tmp = tempfile.mkstemp(prefix=".authmove-", dir=os.path.dirname(path))\n    try:',
                  '    tmp = path + ".new"\n    fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)\n    try:'),
 ('migsource', MIG, 'exec python3 - "$@"',
                  '. "$HOME/review/bin/review-env.sh"\nexec python3 - "$@"'),
 ('migscratch', MIG, '    if args.dry_run:\n',
                  '    os.makedirs(os.path.join(review, "data", "tmp"), exist_ok=True)\n    if args.dry_run:\n'),
 ('migcredentials', MIG, '    if moving:\n        os.rename(old, new)',
                  '    if moving:\n        os.rename(old, new)\n        os.unlink(os.path.join(new, "codex-personal", "auth.json"))'),
 ('denyambiguous', RUN, 'if path not in ("/", "~") and (not anchored or anchored.startswith("/") or\n                                   anchored.endswith("/") or "//" in anchored):',
                  'if False:'),
 ('authphysical', ENV, '        "$review_root/"*) echo "$root is inside the granted review root" >&2; return 1 ;;',
                  '        "$review_root/"*) : ;;'),
 ('layoutboundary', "docs/review-box.md", 'Relative paths such as `../review.auth` can still reach it.',
                  'No relative path reaches it.'),
 ('layouttable', "docs/review-box.md", '| `~/review/work/` |',
                  '\nparagraph\n| `~/review/work/` |'),
 # the accounts live outside the directory the agent is handed
 ("authinsideroot", ENV, 'export REVIEW_AUTH="${REVIEW_AUTH:-$REVIEW_ROOT.auth}"',
                         'export REVIEW_AUTH="${REVIEW_AUTH:-$REVIEW_ROOT/auth}"'),
 # choosing an account from the policy, without acting on it
 ("selorder", ACC, "    for name in names:", "    for name in reversed(names):"),
 ("selthreshold", ACC, 'elif rec["free_pct"] <= min_free:', 'elif rec["free_pct"] < 0:'),
 ("selunknown", ACC, '        if rec.get("error"):', '        if False:'),
 ("selnofree", ACC, '        elif rec.get("free_pct") is None:', '        elif False:'),
 ("selpathname", ACC, '    if os.sep in name or name in (os.curdir, os.pardir):',
                      '    if False:'),
 ("selcontain", ACC, "    if not real.startswith(root + os.sep) and real not in own:",
                     "    if False:"),
 ("selnopolicy", ACC, '        raise PolicyError("cannot read %s: %s" % (path, e))',
                      '        return {"roles": {}}'),
 ("seldupe", ACC, "            if len(set(names)) != len(names):", "            if False:"),
 ("selunknowntool", ACC, "            if tool not in quota.TOOLS:", "            if False:"),
 ("selemptylist", ACC, "            if not isinstance(names, list) or not names or \\",
                       "            if False and (not isinstance(names, list) or not names) or \\"),
 ("selfresh", ACC, "            if age is not None and 0 <= age <= fresh_minutes:",
                   "            if age is not None:"),
 ("selstale", ACC, "        rec = quota.recorded().get(key)", "        rec = None"),
 ("selnorecord", ACC, "    if not record:\n        return", "    if True:\n        return"),
 ("selalwaysrecord", ACC, "    if not record:\n        return", "    if False:\n        return"),
 # times on the page are the box's own, not the CLIs' UTC
 ("rolloverutc", PAGE, "        soonest.astimezone().strftime('%a %d %b %H:%M'),",
                       "        soonest.strftime('%a %d %b %H:%M'),"),
 # the page is published; identities are masked on it
 ("nomask", PAGE, "_mask(html.escape(q.get('account')))", "html.escape(q.get('account'))"),
 ("maskall", PAGE, '        return "%s&hellip;%s@%s" % (local[0], local[-1], domain) if len(local) > 2 \\\n            else "&hellip;@%s" % domain',
                   '        return "&hellip;"'),
 # the Quotas section: recorded readings, never a live one
 ("quotarownewest", QUO, '        if key[0] and key not in newest:',
                         '        if key[0]:'),
 ("quotarowerror", PAGE, "    if q.get('error'):", '    if False:'),
 ("quotarollscoped", PAGE, "        if w.get('scoped') or not w.get('resets_at'):",
                           "        if not w.get('resets_at'):"),
 ("quotarollsoonest", PAGE, '    soonest = min(when)', '    soonest = max(when)'),
 ("quotalowmark", PAGE, "            '' if free is None or free > 5 else 'bad',",
                        "            '',"),
 ("quotanoreadings", PAGE, "if not qrows:", "if False:"),
 # repeating a switch is a no-op, not a cycle
 ("noalready", AUT, '[ "$(readlink "$link" 2>/dev/null)" = "$tool-$acct" ] && already=1',
                    'already=0'),
 # signing an account in on a box with no browser
 ("nodeviceauth", AUT, 'codex login --device-auth', 'codex login'),
 ("noapikeywarning", AUT, 'echo "machine instead. Do not use --with-api-key: a key bills"',
                          'true'),
 # reading what each account has left, without acting on it
 ("quotaworst", QUO, 'return round(100.0 - max(w["used_pct"] for w in usable), 1)',
                     'return round(100.0 - min(w["used_pct"] for w in usable), 1)'),
 ("quotascoped", QUO, 'usable = [w for w in windows if not w.get("scoped")',
                      'usable = [w for w in windows if True or not w.get("scoped")'),
 ("quotaraises", QUO, '    except Exception as e:                       # observation must not raise\n        rec["error"] = "%s: %s" % (type(e).__name__, e)',
                      '    except ValueError as e:\n        rec["error"] = "%s: %s" % (type(e).__name__, e)'),
 ("quotanorecord", QUO, '    if record:', '    if False:'),
 ("quotaalwaysrecord", QUO, '    if record:', '    if True:'),
 ("quotadedup", QUO, '        if real in seen:', '        if False:'),
 ("quotastdin", QUO, "        proc.stdin.write(req)\n        proc.stdin.flush()",
                     "        proc.stdin.write(req)\n        proc.stdin.close()"),
 # the run's own usage probe can leave the OAuth lock the agent dies on
 ("lockbeforelaunch", RUN, 'clear_stale_oauth_lock "$CLAUDE_DIR"\n\nstdbuf -oL -eL claude -p',
                           '\nstdbuf -oL -eL claude -p'),
 ("probesilentrc", PRB, 'echo "claude -p /usage exited non-zero - no reading taken" >&2',
                        'true'),
 ("probesilentparse", PRB, 'if [ "$LIMITED" -eq 0 ] && ! tail -1 "$OUT" 2>/dev/null',
                           'if false && ! tail -1 "$OUT" 2>/dev/null'),
 # a run behind the lock has run nothing, and owes nothing
 ("noqueued", PAGE, "        r['status'] = 'queued'\n", "        pass\n"),
 ("queuedtokens", PAGE, "    if r['status'] == 'queued':\n        r['ctok'], r['cwt'] = 0, 0",
                        "    if False:\n        r['ctok'], r['cwt'] = 0, 0"),
 ("windowfromstart", PAGE, "        r['ctok'], r['cwt'] = claude_between(r.get('acquired') or r['start'],",
                           "        r['ctok'], r['cwt'] = claude_between(r['start'],"),
 ("queuedwait", PAGE, "        r['waited'] = int((now - start).total_seconds() // 60)",
                      "        r['waited'] = None"),
 # a run killed mid-flight never writes its own finish line
 ("nostall", PAGE, "        if last and now - last > grace and last > start:",
                   "        if False:"),
 ("stallgrace", PAGE, "STALL_GRACE = datetime.timedelta(minutes=30)",
                      "STALL_GRACE = datetime.timedelta(minutes=0)"),
 ("stalllockwait", PAGE, "        if w and 'lock acquired' not in txt:",
                         "        if False:"),
 # a refusal that nobody can see is a slot that goes quiet
 ("refusalbeforelog", RUN, 'export REVIEW_ROLE="$ROLE"\nif ! clear_inherited_credentials',
                           'export REVIEW_ROLE="$ROLE"\nexec >/dev/null\nif ! clear_inherited_credentials'),
 # the dashboard: it describes the accounts the roles select
 ("pageaccounts", QUO, 'sorted(glob.glob(os.path.join(glob.escape(AUTH), tool + "-*")))', "[]"),
 ("pageown", QUO, 'for d in [os.path.join(HOME, "." + tool)] + \\', 'for d in [] + \\'),
 ("pagestatus", PAGE, "elif re.search(r'status=wrong-\\w+-account', txt):",
                      "elif 'status=wrong-claude-account' in txt:"),
 ("probefollow", PRB, 'PROBE_DIR=$(role_config_dir claude default "$PROBE_DIR")',
                      'PROBE_DIR=""'),
 ("proberunenv", PRB, 'if [ -z "${CLAUDE_CONFIG_DIR:-}" ] && [ -z "${REVIEW_ROLE:-}" ]; then',
                      'if true; then'),
 ("earlyprobe", AUT, '    lockf="$AUTH/.$tool-$role.lock"',
                     '    got=$(account_of "$tool" "$dir")\n    lockf="$AUTH/.$tool-$role.lock"'),

 # --- the quota policy, and the money it must not spend ------------------------
 ('selovererage', ACC, '        elif rec.get("ordinary_usage_allowed") is False:',
                       '        elif False:'),
 ('selovereager', ACC, '        elif rec.get("ordinary_usage_allowed") is False:',
                       '        elif rec.get("ordinary_usage_allowed") is not True:'),
 ('selpartial', ACC, '        short = [d for d in decisions if not d["chosen"]]',
                     '        short = []'),
 ('selexitcode', ACC, '            return NOTHING_USABLE\n', '            return 1\n'),
 ('selwalkstdout', ACC,
  '                    "CHOSEN" if step.get("chosen") else step.get("skipped")),\n                    file=sys.stderr)',
  '                    "CHOSEN" if step.get("chosen") else step.get("skipped")))'),
 ('polignored', RUN, '    [ -e "$REVIEW_AUTH/policy.json" ] || {',
                     '    [ -e "/nonexistent/policy.json" ] || {'),
 ('poldefercarries', RUN,
  '           echo "finish=$(date -Is) status=deferred-no-quota"\n           exit 0 ;;',
  '           return 0 ;;'),
 ('polbrokencarries', RUN,
  '        *) echo "FATAL: the account policy could not be applied (accounts.py exit $rc)"\n           echo "finish=$(date -Is) status=account-policy-error"\n           exit 1 ;;',
  '        *) return 0 ;;'),
 ('poltrustspath', RUN,
  '        account_dir_ok "$tool" "$dir" "the $tool account $name" || {\n            echo "FATAL: the account policy chose $name for $tool, which is not"\n            echo "       usable as an account directory"\n            echo "finish=$(date -Is) status=account-policy-error"\n            exit 1; }',
  '        :'),
 ('polnolocksweep', RUN, '    clear_stale_oauth_locks\n', ''),
 ('lockskipruns', RUN,
  '        echo "finish=$(date -Is) status=skipped-locked"\n        exit 0',
  '        echo "finish=$(date -Is) status=skipped-locked"'),
 ('pagedeferred', PAGE, "    elif 'status=deferred-no-quota' in txt:", "    elif False:"),
 ('pagepolicyerr', PAGE, "    elif 'status=account-policy-error' in txt:", "    elif False:"),
 ('pagedeferfail', PAGE, "    elif r['status'] not in ('running', 'queued', 'deferred'): m['fail'] += 1",
                         "    elif r['status'] not in ('running',): m['fail'] += 1"),
]

# An unrelated failure is not evidence for a particular guard. Each mutation
# must break its regression after the complete, unchanged suite has passed.
REGRESSION = {
    'migancestor': 'AuthRootMove.test_resuming_cannot_treat_home_as_the_account_root',
    'migcontrol': 'AuthRootMove.test_an_unrepresentable_destination_is_refused_before_moving',
    'migchmod': 'AuthRootMove.test_an_already_migrated_box_needs_no_writes',
    'migatomic': 'AuthRootMove.test_an_interruption_leaves_complete_settings_and_can_resume',
    'migwalk': 'AuthRootMove.test_an_unreadable_inventory_is_not_an_empty_root',
    'authowninside': 'Guard.test_a_tool_home_cannot_put_credentials_back_inside_review',
    'authtargetinside': 'Guard.test_a_tool_home_cannot_put_credentials_back_inside_review',

    'migprevalidate': 'AuthRootMove.test_all_settings_are_validated_before_any_write',
    'migexit': 'AuthRootMove.test_a_failed_write_is_reported_and_a_rerun_finishes',
    'migresume': 'AuthRootMove.test_a_failed_write_is_reported_and_a_rerun_finishes',
    'migrepeat': 'AuthRootMove.test_an_already_migrated_box_needs_no_writes',
    'migglob': 'AuthRootMove.test_custom_roots_are_not_globs',
    'migpattern': 'Guard.test_migration_rules_work_outside_home_and_with_pattern_characters',
    'migoutsidehome': 'Guard.test_migration_rules_work_outside_home_and_with_pattern_characters',
    'migcanonical': 'AuthRootMove.test_a_destination_alias_into_review_is_refused',
    'migrootlink': 'AuthRootMove.test_symlink_roots_are_refused_without_moving',
    'migdevice': 'AuthRootMove.test_dry_run_refuses_different_filesystems',
    'migcopy': 'AuthRootMove.test_cross_filesystem_rename_failure_never_copies',
    'migpostcheck': 'AuthRootMove.test_the_moved_root_is_checked_again_before_writes',
    'migabslink': 'AuthRootMove.test_links_whose_meaning_changes_are_refused_before_the_move',
    'migrellink': 'AuthRootMove.test_links_whose_meaning_changes_are_refused_before_the_move',
    'migownlink': 'AuthRootMove.test_links_whose_meaning_changes_are_refused_before_the_move',
    'migdangling': 'AuthRootMove.test_a_dangling_link_is_refused_before_the_move',
    'migdestination': 'AuthRootMove.test_planted_write_destinations_cannot_overwrite_credentials',
    'migtemp': 'AuthRootMove.test_a_name_planted_after_validation_cannot_redirect_a_write',
    'migsource': 'AuthRootMove.test_deployed_environment_is_not_needed',
    'migscratch': 'AuthRootMove.test_a_dry_run_changes_nothing_but_names_every_edit',
    'migcredentials': 'Guard.test_migration_preserves_credentials_and_passes_the_real_preflight',
    'denyambiguous': 'Guard.test_ambiguous_rule_roots_are_refused',
    'authphysical': 'Guard.test_an_auth_root_inside_review_is_refused_even_through_an_alias',
    'layoutboundary': 'Guard.test_layout_documentation_keeps_the_table_and_explains_the_boundary',
    'layouttable': 'Guard.test_layout_documentation_keeps_the_table_and_explains_the_boundary',

    'reresolve': 'Guard.test_a_switch_after_validation_does_not_resolve_the_role_again',
    'denyfsroot': 'Guard.test_read_denials_can_cover_the_home_or_filesystem_root',
    'denytilderoot': 'Guard.test_read_denials_can_cover_the_home_or_filesystem_root',
    'denydot': 'Guard.test_filesystem_normalization_does_not_prove_a_read_pattern',
    'baretool': 'Guard.test_disabling_read_alone_does_not_deny_the_path_to_other_readers',
    'denylist': 'Guard.test_a_deny_object_is_not_a_cli_permission_list',
    'ruleunescape': 'Guard.test_rule_escaping_and_pattern_escaping_are_separate',
    'ruleescape': 'Guard.test_rule_escaping_and_pattern_escaping_are_separate',
    'loginescapelevel': 'Guard.test_rule_escaping_and_pattern_escaping_are_separate',
    'unusedprovider': 'Guard.test_an_unused_provider_definition_does_not_route_requests',
    'probebroken': 'UsageProbe.test_a_broken_hourly_role_does_not_probe_the_fallback',
    'probeownrun': 'UsageProbe.test_a_run_using_the_tools_home_does_not_follow_a_later_switch',
    'quotaglob': 'Dashboard.test_glob_characters_in_an_account_name_cannot_select_another_account',
    'authglob': 'Dashboard.test_glob_characters_in_the_auth_root_do_not_hide_accounts',
    'claudeglob': 'Dashboard.test_glob_characters_in_a_claude_directory_do_not_hide_transcripts',
    'logglob': 'Dashboard.test_glob_characters_in_home_do_not_hide_run_logs',
    'quotadeleted': 'Dashboard.test_a_deleted_recorded_home_does_not_borrow_another_accounts_samples',
    'denysubstring': 'Guard.test_the_deny_rule_must_cover_reads_of_this_whole_auth_tree',
    'denyescaping': 'Guard.test_custom_auth_paths_are_escaped_in_login_and_refusal_instructions',
    'loginescaping': 'Guard.test_custom_auth_paths_are_escaped_in_login_and_refusal_instructions',
    'permissionfinish': 'Guard.test_a_permission_refusal_finishes_the_logged_run',
    'workfinish': 'Guard.test_a_missing_work_directory_finishes_the_logged_run',
    'pageterminal': 'Guard.test_a_permission_refusal_finishes_the_logged_run',
    'pagefailcount': 'Guard.test_a_permission_refusal_finishes_the_logged_run',
    'denytool': 'Guard.test_the_deny_rule_must_cover_reads_of_this_whole_auth_tree',
    'denycoverage': 'Guard.test_the_deny_rule_must_cover_reads_of_this_whole_auth_tree',
    'denyancestor': 'Guard.test_an_ancestor_read_denial_is_sufficient',
    'denysuggestion': 'Guard.test_the_suggested_read_rule_is_absolute_and_satisfies_the_preflight',
    'loginsettings': 'Guard.test_login_instructions_supply_working_settings',
    'installsettings': 'Guard.test_install_instructions_supply_working_settings',
    'readmesettings': 'Guard.test_readme_instructions_supply_working_settings',
    'usetool': 'Switching.test_unknown_tools_cannot_switch_roles',
    'logintool': 'Switching.test_unknown_tools_cannot_create_login_directories',
    'plainname': 'Switching.test_role_and_account_names_are_checked_before_paths_are_used',
    'rolealias': 'Switching.test_an_alias_of_the_current_role_is_refused_before_switching',
    'quotaenv': 'Dashboard.test_codex_card_follows_a_named_default_role_not_the_publisher',
    'quotamixed': 'Dashboard.test_codex_deltas_follow_each_logged_account_even_after_a_switch',
    'quotaunknown': 'Dashboard.test_codex_usage_without_matching_account_attribution_stays_unknown',
    'quotaidentity': 'Dashboard.test_codex_usage_without_matching_account_attribution_stays_unknown',
    'quotadangling': 'Dashboard.test_a_dangling_codex_role_does_not_show_the_fallbacks_meter',
    'quotaown': 'Dashboard.test_an_absent_codex_default_role_still_uses_the_tools_own_home',
    'quotalabel': 'Dashboard.test_codex_card_follows_a_named_default_role_not_the_publisher',
    'quotaspace': 'Dashboard.test_codex_deltas_follow_each_logged_account_even_after_a_switch',
    'rootowner': 'Guard.test_an_auth_root_we_do_not_own_stops_the_run',
    'unknownid': 'Guard.test_an_unknown_identity_with_a_record_stops_the_run',
    'rejectcodex': 'Guard.test_a_codex_account_file_that_disagrees_stops_the_run',
    'disagree': 'Guard.test_the_two_identity_sources_disagreeing_stops_the_run',
    'badrecord': 'Guard.test_an_unreadable_account_record_says_which_problem_it_is',
    'noflock': 'Switching.test_one_switch_at_a_time',
    'earlyrelease': 'Switching.test_the_lock_is_held_until_the_switch_has_been_validated',
    'noduddash': 'Switching.test_a_revert_to_an_option_shaped_target_is_not_claimed_falsely',
    'noswitchback': 'Switching.test_a_revert_to_an_option_shaped_target_is_not_claimed_falsely',
    'lyingrevert': 'Switching.test_a_revert_that_fails_says_so',
    'nolocksymlink': 'Switching.test_a_symlinked_lock_is_refused_rather_than_written_through',
    'norootfirst': 'Switching.test_an_unsafe_root_is_refused_before_the_lock_is_opened',
    'nostatusrec': 'StatusView.test_a_record_the_runner_cannot_read_is_flagged',
    'noconflict': 'StatusView.test_a_directory_that_disagrees_with_the_cli_is_flagged',
    'alwaysconflict': 'StatusView.test_a_matching_identity_is_not_flagged_as_a_conflict',
    'nomismatch': 'StatusView.test_a_record_naming_another_account_is_flagged',
    'noidunknown': 'StatusView.test_an_identity_that_cannot_be_checked_is_flagged',
    'nodefaultrow': 'StatusView.test_a_missing_default_role_is_shown_as_the_tools_own_account',
    'statusapikey': 'StatusView.test_a_codex_api_key_is_not_shown_as_an_account',
    'statusmethod': 'StatusView.test_a_token_login_is_not_shown_as_the_subscription',
    'statusprovider': 'StatusView.test_a_cloud_provider_is_not_shown_as_the_subscription',
    'statusdir': 'StatusView.test_credentials_read_from_another_directory_are_flagged',
    'statuspartial': 'StatusView.test_a_partial_answer_from_the_cli_is_flagged',
    'statusfailedunset': 'StatusView.test_a_credential_variable_that_cannot_be_unset_is_reported',
    'statusstderr': 'StatusView.test_a_warning_on_stderr_is_not_part_of_the_directory',
    'blindaccount': 'StatusView.test_it_reports_the_address_a_signed_in_role_will_run_as',
    'lazyswitch': 'Switching.test_switching_to_the_account_already_in_place_is_still_checked',
    'noenvsweep': 'Guard.test_an_alternate_credential_store_does_not_reach_the_cli',
    'nounsetcheck': 'Guard.test_a_credential_variable_that_cannot_be_unset_stops_the_run',
    'skipunsets': 'Guard.test_a_codex_credential_variable_is_cleared',
    'suffixgap': 'Guard.test_a_token_variable_with_a_suffix_does_not_reach_the_cli',
    'noopenai': 'Guard.test_an_openai_key_does_not_reach_the_cli',
    'nocodex': 'Guard.test_a_codex_credential_variable_is_cleared',
    'nomethod': 'Guard.test_a_token_login_stops_the_run',
    'noprovider': 'Guard.test_a_cloud_provider_stops_the_run',
    'noclidir': 'Guard.test_credentials_read_from_another_directory_stop_the_run',
    'partialmeta': 'Guard.test_a_cli_that_reports_none_of_those_is_refused',
    'codexprovider': 'Guard.test_a_config_that_cannot_be_parsed_stops_the_run',
    'codexapikey': 'Guard.test_a_codex_api_key_stops_the_run',
    'implicitkey': 'Guard.test_an_api_key_with_no_auth_mode_stops_the_run',
    'nourlscan': 'Guard.test_a_redefined_openai_provider_stops_the_run',
    'noenvkey': 'Guard.test_a_provider_key_variable_stops_the_run',
    'noreqauth': 'Guard.test_a_provider_that_waives_openai_auth_stops_the_run',
    'noprofileprov': 'Guard.test_a_provider_named_in_a_profile_stops_the_run',
    'nounreadable': 'Guard.test_a_config_that_cannot_be_parsed_stops_the_run',
    'fieldsplit': 'Guard.test_an_account_directory_whose_path_has_a_space',
    'urlscheme': 'Guard.test_endpoint_urls_are_parsed_as_urls',
    'urlport': 'Guard.test_endpoint_urls_are_parsed_as_urls',
    'mcpfalsepositive': 'Guard.test_mcp_routing_and_documentation_do_not_select_inference_credentials',
    'bearertoken': 'Guard.test_provider_credential_overrides_are_refused',
    'credstore': 'Guard.test_an_alternate_codex_credential_store_is_refused',
    'forcedlogin': 'Guard.test_a_forced_api_login_is_refused',
    'danglingconfig': 'Guard.test_a_dangling_codex_config_is_not_absent',
    'statusdetail': 'Guard.test_a_forced_api_login_is_refused',
    'statusshape': 'Guard.test_status_refuses_different_identity_shapes_like_the_runner',
    'statusunsafeprobe': 'StatusView.test_a_credential_variable_that_cannot_be_unset_is_reported',
    'cliexit': 'Guard.test_a_failed_cli_exit_is_not_authentication',
    'statusexit': 'Guard.test_a_failed_cli_exit_is_not_authentication',
    'metacontrol': 'Guard.test_invalid_metadata_is_refused_instead_of_treated_as_absent',
    'metaempty': 'Guard.test_invalid_metadata_is_refused_instead_of_treated_as_absent',
    'metaloggertype': 'Guard.test_invalid_metadata_is_refused_instead_of_treated_as_absent',
    'statusloggertype': 'Guard.test_invalid_metadata_is_refused_instead_of_treated_as_absent',
    'metawhitespace': 'Guard.test_a_directory_with_trailing_space_is_preserved',
    'cliidentity': 'Guard.test_raw_cli_and_directory_identities_do_not_leak_into_logs',
    'recordidentity': 'Guard.test_raw_cli_and_directory_identities_do_not_leak_into_logs',
    'staterecordidentity': 'Guard.test_raw_cli_and_directory_identities_do_not_leak_into_logs',
    'codextokens': 'Guard.test_incomplete_codex_tokens_are_not_a_login',
    'codexmode': 'Guard.test_an_unsupported_codex_auth_mode_is_not_a_subscription',
    'codexidentity': 'Guard.test_a_codex_identity_cannot_contain_a_secret',
    'nometa': 'Guard.test_a_cli_that_reports_none_of_those_is_refused',
    'statusnometa': 'Guard.test_no_cli_metadata_is_also_refused_by_status',
    'rolecase': 'Guard.test_github_reference_case_and_url_form_do_not_change_the_role',
    'roleurl': 'Guard.test_github_reference_case_and_url_form_do_not_change_the_role',
    'mcpcallback': 'Guard.test_mcp_routing_and_documentation_do_not_select_inference_credentials',
    'codexjwt': 'Guard.test_an_unparseable_codex_id_token_is_not_a_login',
    'urlparser': 'Guard.test_endpoint_urls_are_parsed_as_urls',
    'oneconfiglayer': 'Guard.test_a_profile_layer_beside_the_config_is_checked_too',
    'otelscan': 'Guard.test_a_telemetry_exporter_pointing_elsewhere_stops_the_run',
    'nocreddeny': 'Guard.test_credentials_inside_the_granted_directory_must_be_denied',
    'credrealpath': 'Dashboard.test_it_does_not_count_one_transcript_reached_two_ways',
    'migmerge': 'AuthRootMove.test_it_refuses_to_merge_two_account_roots',
    'migstale': 'AuthRootMove.test_existing_denials_are_preserved',
    'migdry': 'AuthRootMove.test_a_dry_run_changes_nothing_but_names_every_edit',
    'authinsideroot': 'Guard.test_the_accounts_are_not_inside_the_directory_the_agent_is_given',
    'selorder': 'Accounts.test_the_first_account_with_quota_wins',
    'selthreshold': 'Accounts.test_the_threshold_is_a_floor_an_account_must_clear',
    'selunknown': 'Accounts.test_a_failed_reading_is_not_treated_as_quota',
    'selnofree': 'Accounts.test_a_reading_with_no_figure_and_no_error_is_not_quota_either',
    'selpathname': 'Accounts.test_a_name_with_a_separator_is_refused_even_inside_the_root',
    'selcontain': 'Accounts.test_an_account_symlinked_out_of_the_root_is_refused',
    'selnopolicy': 'Accounts.test_without_a_policy_it_refuses_rather_than_guessing',
    'seldupe': 'Accounts.test_a_policy_repeating_an_account_is_refused',
    'selunknowntool': 'Accounts.test_a_policy_naming_an_unknown_tool_is_refused',
    'selemptylist': 'Accounts.test_a_policy_with_an_empty_list_is_refused',
    'selfresh': 'Accounts.test_a_stale_reading_is_not_used',
    'selstale': 'Accounts.test_a_recent_reading_is_used_rather_than_asking_the_account',
    'selnorecord': 'Accounts.test_record_writes_one_line_per_decision',
    'selalwaysrecord': 'Accounts.test_it_writes_nothing_unless_asked',
    'rolloverutc': 'Dashboard.test_rollover_is_shown_in_the_boxs_own_time_not_the_clis',
    'nomask': 'Dashboard.test_the_page_is_published_so_identities_are_masked',
    'maskall': 'Dashboard.test_a_masked_address_keeps_its_domain',
    'quotarownewest': 'Dashboard.test_the_newest_reading_wins',
    'quotarowerror': 'Dashboard.test_a_reading_that_failed_shows_why_rather_than_a_figure',
    'quotarollscoped': 'Dashboard.test_a_per_model_window_is_shown_but_does_not_set_the_rollover',
    'quotarollsoonest': 'Dashboard.test_rollover_is_the_soonest_window_that_gates_work',
    'quotalowmark': 'Dashboard.test_an_account_at_the_threshold_is_marked',
    'quotanoreadings': 'Dashboard.test_with_no_readings_it_says_so_rather_than_showing_nothing',
    'noalready': 'Switching.test_repeating_a_switch_already_in_place_is_not_a_cycle',
    'nodeviceauth': 'Switching.test_codex_login_says_how_to_sign_in_without_a_browser',
    'noapikeywarning': 'Switching.test_codex_login_warns_off_an_api_key',
    'quotaworst': 'Quota.test_free_is_what_is_left_of_the_worst_window',
    'quotascoped': 'Quota.test_a_per_model_window_is_recorded_but_does_not_decide',
    'quotaraises': 'Quota.test_a_missing_cli_is_recorded_not_raised',
    'quotanorecord': 'Quota.test_record_appends_one_line_per_account',
    'quotaalwaysrecord': 'Quota.test_it_writes_nothing_unless_asked',
    'quotadedup': 'Quota.test_every_account_is_read_once',
    'quotastdin': 'Quota.test_it_reads_codexs_live_meter_not_the_rollout_files',
    'lockbeforelaunch': 'Guard.test_a_lock_left_by_the_start_probe_is_cleared_before_the_agent',
    'probesilentrc': 'Guard.test_a_probe_whose_cli_fails_says_so',
    'probesilentparse': 'Guard.test_a_probe_that_takes_no_reading_says_so',
    'noqueued': 'Dashboard.test_a_run_behind_the_lock_is_not_shown_as_running',
    'queuedtokens': 'Dashboard.test_a_queued_run_is_credited_with_no_tokens',
    'windowfromstart': 'Dashboard.test_a_run_that_waited_counts_only_from_when_it_got_the_lock',
    'queuedwait': 'Dashboard.test_a_queued_run_shows_its_wait_where_the_wait_belongs',
    'nostall': 'Dashboard.test_a_run_that_stopped_writing_is_not_still_running',
    'stallgrace': 'Dashboard.test_a_run_still_writing_is_left_alone',
    'stalllockwait': 'Dashboard.test_a_run_queued_on_the_lock_is_not_called_dead',
    'refusalbeforelog': 'Guard.test_a_refusal_is_written_to_the_run_log',
    'pageaccounts': 'Dashboard.test_it_counts_the_account_a_role_selects',
    'pageown': 'Dashboard.test_it_counts_the_tools_own_directory',
    'pagestatus': 'Dashboard.test_a_refused_codex_run_is_shown_as_refused',
    'probefollow': 'UsageProbe.test_the_hourly_probe_reads_the_account_the_role_selects',
    'nofallbackpin': 'Guard.test_a_symlinked_tool_home_is_pinned_even_with_no_role_link',
    'proberunenv': 'UsageProbe.test_a_run_probe_keeps_the_account_the_run_selected',
    'earlyprobe': 'Switching.test_an_unsafe_account_is_refused_before_the_cli_reads_it',

    'selovererage': 'Accounts.test_an_account_past_its_included_allowance_is_passed_over',
    'selovereager': 'Accounts.test_a_tool_that_reports_no_allowance_field_is_not_refused',
    'selpartial': 'Accounts.test_select_answers_with_nothing_at_all_when_one_tool_is_short',
    'selexitcode': 'Accounts.test_select_says_nothing_usable_with_an_exit_code_of_its_own',
    'selwalkstdout': 'Accounts.test_select_keeps_the_walk_off_the_answer',
    'polignored': 'Guard.test_the_policy_moves_a_run_off_a_spent_account',
    'poldefercarries': 'Guard.test_a_run_defers_when_every_listed_account_is_spent',
    'polbrokencarries': 'Guard.test_a_policy_that_cannot_be_applied_stops_the_run',
    'poltrustspath': 'Guard.test_the_runner_does_not_take_the_selectors_word_for_the_path',
    'polnolocksweep': 'Guard.test_a_lock_left_in_another_account_is_cleared_before_it_is_read',
    'lockskipruns': 'Guard.test_a_run_that_loses_the_lock_selects_nothing',
    'pagedeferred': 'Dashboard.test_a_deferred_run_is_shown_as_held_by_quota_not_as_running',
    'pagepolicyerr': 'Dashboard.test_a_policy_that_could_not_be_applied_is_shown_as_a_failure',
    'pagedeferfail': 'Dashboard.test_a_deferred_run_counts_against_quota_and_not_against_failures',
}

def main():
    only = sys.argv[1:]
    work = tempfile.mkdtemp(prefix="mutate-", dir=WORK)
    home = os.path.join(work, "h"); os.makedirs(home)
    tree = os.path.join(work, "r")
    bad = 0
    selected = [m for m in M if not only or m[0] in only]
    test_env = {"HOME": home, "PATH": "/usr/bin:/bin", "TMPDIR": work,
                "PYTHONDONTWRITEBYTECODE": "1"}
    tests = sorted(t for t in os.listdir(os.path.join(SRC, "runner/tests"))
                   if t.startswith("test_") and t.endswith(".py"))
    try:
        # A broken baseline is not evidence that a mutation was caught.
        for t in tests:
            result = subprocess.run(["python3", os.path.join(SRC, "runner/tests", t)],
                                    capture_output=True, text=True, env=test_env)
            if result.returncode:
                print("baseline failed: " + t)
                print(result.stdout + result.stderr)
                return 1
        print("%d test files pass" % len(tests), flush=True)
        for name, files, old, new in selected:
            shutil.rmtree(tree, ignore_errors=True)
            shutil.copytree(SRC, tree, ignore=shutil.ignore_patterns(
                ".git", ".test-work", "__pycache__"))
            for f in ((files,) if isinstance(files, str) else files):
                path = os.path.join(tree, f)
                s = io.open(path).read()
                if s.count(old) != 1:
                    print("  %-16s NOT APPLIED (%d matches in %s)"
                          % (name, s.count(old), f)); bad += 1; break
                io.open(path, "w").write(s.replace(old, new, 1))
            else:
                case = REGRESSION[name]
                # find the class rather than guessing from two filenames: a
                # third test file silently sent every case to the wrong one,
                # which reads as NOT CAUGHT whatever the mutation did
                cls = case.split(".")[0]
                test = next((t for t in tests
                             if re.search(r"^class %s\(" % re.escape(cls),
                                          io.open(os.path.join(tree, "runner/tests", t)).read(),
                                          re.M)), None)
                if test is None:
                    print("  %-16s NO SUCH TEST CLASS: %s" % (name, cls))
                    bad += 1
                    continue
                r = subprocess.run(["python3", os.path.join(tree, "runner/tests", test), case, "-f"],
                                   capture_output=True, text=True, env=test_env)
                output = r.stdout + r.stderr
                failures = re.findall(r"^FAIL: (.+)$", output, re.M)
                if failures and not re.search(r"^ERROR:", output, re.M):
                    print("  %-16s caught: %s" % (name, failures[0]))
                else:
                    print("  %-16s NOT CAUGHT" % name); bad += 1
                    if r.returncode:
                        print(output)
                sys.stdout.flush()
    finally:
        shutil.rmtree(work, ignore_errors=True)
    print("%d of %d mutations unaccounted for" % (bad, len(selected)))
    return 1 if bad else 0

sys.exit(main())
